#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct  (Madagascar Script)
#
# Purpose: Kirchhoff Newton modeling of a multi layer velocity model.
#
# Site: https://dirack.github.io
#
# Programer: Rodolfo A. C. Neves (Dirack) 03/02/2021
#
# Email: rodolfo_profissional@hotmail.com
#
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Madagascar package
from rsf.proj import *

# Recipes
from rsf.recipes.kimodel import multiLayerModel as mlmod
from rsf.recipes.kimodel import kirchhoffNewtonModeling as kinewmod

xmax = 6.0
zmax = 4.0

layers = ((1.00,1.20,0.90,1.00),
	  (1.85,1.85,1.85,1.85))

velocities = (1.508,
	      1.690,
	      2.0)

# Generate multi layer model and data cube
mlmod(interfaces='interfaces',
	dipsfile='interfacesDip',
	modelfile='mod1',
	xmax=xmax,
	zmax=zmax,
	layers=layers,
	velocities=velocities)

# Generate a modeled data cube
kinewmod(reflectors='interfaces',
	reflectorsDip='interfacesDip',
	filename='multiLayerDataCube',
	velocities=velocities,
	nt=1001,
	dt=0.004,
	ns=241,
	ds=0.025,
	nh=161,
	dh=0.025)

